import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import jobRoutes from './job.routes';
import appliedRoutes from './applied.routes';
import subscriptionRoutes from './subscription.routes';
import alertRoutes from './alert.routes';
import deviceRoutes from './device.routes';
import hirerRoutes from './hirer.routes';
import notificationRoutes from './notification.routes';
import autoApplyRoutes from './autoApply.routes';
import chatRoutes from './chat.routes';
import interviewRoutes from './interview.routes';
import salaryRoutes from './salary.routes';
import companyRoutes from './company.routes';
import aiRoutes from './ai.routes';
import skillAssessmentRoutes from './skillAssessment.routes';
import mockInterviewRoutes from './mockInterview.routes';
import teamRoutes from './team.routes';
import gamificationRoutes from './gamification.routes';
import referralRoutes from './referrals.routes';

const router = Router();

router.use('/', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/jobs', jobRoutes);
router.use('/applied', appliedRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/alerts', alertRoutes);
router.use('/devices', deviceRoutes);
router.use('/hirer', hirerRoutes);
router.use('/notifications', notificationRoutes);
router.use('/auto-apply', autoApplyRoutes);
router.use('/conversations', chatRoutes);
router.use('/interviews', interviewRoutes);
router.use('/salary-insights', salaryRoutes);
router.use('/companies', companyRoutes);
router.use('/ai', aiRoutes);
router.use('/skill-assessments', skillAssessmentRoutes);
router.use('/mock-interviews', mockInterviewRoutes);
router.use('/hirer/team', teamRoutes);
router.use('/seeker', gamificationRoutes);
router.use('/seeker/referrals', referralRoutes);

export default router;
